### PR TITLE
Add callbacks for HOSTDOWNTIME and SERVICEDOWNTIME macros

### PR DESCRIPTION
**Pull request by HubLot**
Hi,

This is a patch for the issue #1409.

### CODE REVIEW

**Comment by naparuba** [comment]
Thanks ^^

**Comment by jylenhofgfi** [comment]
Is the fix the same for 1.4 branch ?

**Comment by naparuba** [comment]
yes, this part of code did not change since the first shinken version :)

**Comment by jylenhofgfi** [comment]
OK.... 
The value are OK for services, but for some hosts there's something wrong... with negative values

Did a little look around and found this on my shinken 1.4 installation : 

echo -e "GET services\nColumns : description scheduled_downtime_depth\n"|socat - TCP4:127.0.0.1:50000,crnl |grep -v 0
# echo -e "GET hosts\nColumns : name scheduled_downtime_depth\n"|socat - TCP4:127.0.0.1:50000,crnl|grep -v 0
;FRRDAS14;-1
;FRRDAVM11;-1
;FRRDAVM12;-1
;FRRDAVM25;1
;FRRDAVM59;-1
;FRRDAVM97;-2
;FRRDAVMB6;-1
;FRRDAVMB7;-1
;FRRDAVMB8;-1
;FRRDAVMB9;-1
;FRRDAVME3;-1
;FRRDAVME8;1
;FRRDAVME9;1
;FRRFAS12;-2
;FRRFAS13;-4

**Pull request merged**
