### PR TITLE
Rework setup.py (virtualenv-compatible)

### PR DESCRIPTION
**Pull request by titilambert**
Rebase of  #1428 from Shinken 2.2

You can now install Shinken like this: 
 - Linux: 
 ```$ sudo python setup.py install --prefix=/```
 - FreeBSD: ```$ sudo python setup.py install --prefix=/usr/local```
Or in virtualenv:
 - ```(env) $ python setup.py install```

Still missing:
 - Init scripts are NOT installed by new setup.py.

About file names, it just about how setuptools handle all of this.
The best thing to understand what we did, is to do:

```
cd /tmp
git clone git@github.com:titilambert/shinken.git
cd shinken
git checkout setup_py
virtualenv env
. env/bin/active
python setup.py install
```
And look in env folder:

```
ls env/bin
ls env/etc
ls env/var
which shinken
which shinken-arbiter
```

Also, you can have a dev environment with:
```
cd /tmp
git clone git@github.com:titilambert/shinken.git
git checkout setup_py
virtualenv env
. env/bin/active
python setup.py develop
python setup.py install_data
```

Also, to launch daemons:
* Arbiter: ```shinken-arbiter -c env/etc/shinken.cfg```
* Broker: ```shinken-broker -c env/etc/shinken/daemons/brokerd.ini```
* Scheduler: ```shinken-scheduler -c env/etc/shinken/daemons/schedulerd.ini```
* Poller: ```shinken-poller -c env/etc/shinken/daemons/pollerd.ini```
* Reactionner: ```shinken-reactionner -c env/etc/shinken/daemons/reactionnerd.ini```
* Receiver: ```shinken-receiver -c env/etc/shinken/daemons/receiverd.ini```

### CODE REVIEW

**Comment by gst** [comment]
please, why not squash together the different "fix" commits :-? 
it's so easy and it's doesn't pollute git history with such "temporary" commits ..

**Comment by Seb-Solon** [comment]
@gst +1

**Comment by Seb-Solon** [comment]
squash squash please

**Comment by titilambert** [comment]
YEAH !
* commits squashed !
* pep8 corrected !
* Go Go Go :)

**Comment by naparuba** [comment]
I don't understand why rename shinken -> shinken_cli and shinken-* into shinken_*.py.

It is required by prb?

**Comment by titilambert** [comment]
it's just because we import these files in new executable files (entrypoint) which will be created during the python setup install.
All those executable files are defined in setup.cfg. There is no change for users, commands "shinken" and “shinken-*" are still there....

**Comment by Seb-Solon** [comment]
can't merge!

**Comment by titilambert** [comment]
Hello !
I just rebased, (baby) one more time...
@naparuba Could you tell me if is it OK for you ?
Thanks !

**Comment by Seb-Solon** [comment]
It's OK for me !

**Pull request merged**
