### PR TITLE
Update macros.rst

### PR DESCRIPTION
**Pull request by jmartignago**

### CODE REVIEW

**Comment by naparuba** [comment]
thanks but why this change?

**Comment by jmartignago** [comment]
Because if you try the command ligne there is a error message

/usr/lib/nagios/plugins/check_ping -H 172.16.1.157 -w 100.0,90% -c 200.0,60%
<wpl> (90) ne peut pas être plus large que <cpl> (60)
check_ping: Impossible de décomposer les arguments
Utilisation:
check_ping -H <host_address> -w <wrta>,<wpl>% -c <crta>,<cpl>%
 [-p packets] [-t timeout] [-4|-6]


root@shinken:/etc/shinken# /usr/lib/nagios/plugins/check_ping -H 172.16.1.157 -w 100.0,60% -c 200.0,90%
PING OK -  Paquets perdus = 0%, RTA = 0.11 ms|rta=0.109000ms;100.000000;200.000000;0.000000 pl=0%;60;90;0

**Comment by naparuba** [comment]
arg ok thanks :)

**Comment by naparuba** [comment]
ps: setting your shinken serve in fr_FR.UTF8 locales can cause you problems, be sure en_US.UTF8 are installed ;)

**Pull request merged**
