### PR TITLE
Fix setup.py to handle sudo python setup.py install

### PR DESCRIPTION
**Pull request by titilambert**
Trying to fix travis problems

### CODE REVIEW

**Comment by titilambert** [comment]
@naparuba This one works with travis

**Comment by naparuba** [comment]
Tahnks, I'm giving a try. @ddurieux will look for freebsd :)

**Comment by naparuba** [comment]
Hi,

stil  /usr/local/bin problem on debian :(

**Comment by naparuba** [comment]
(but travis is happy ^^ )

**Comment by titilambert** [comment]
@naparuba did you use : pip install https://github.com/titilambert/shinken/archive/sudo_setup_py.zip … --install-option="--install-layout=deb"   ?

**Comment by titilambert** [comment]
After IRC reading : 
FreeBSD bugs (ddurieux) :
 - init files not copied in rc.d folder
 - .shinken.ini seems incorrect
Centos 7:
 - Init scripts files seems incorrect (bad VAR and BIN vars)

I will (wednesday) try to fix all of this, but if is too long, maybe the best option is to revert all of this ... :(

But, I will continue with the idea that we should review (probably after the 2.4 release) what we should do/not do with the setup.py ...

Please take a look on salt/ansible and other enterprise grade python softwares ...
PLEASE ... ( sudo pip install salt ) ... PLEASE

**Comment by naparuba** [comment]
On Wed, Apr 8, 2015 at 1:42 AM, Thibault Cohen <notifications@github.com>
wrote:

> After IRC reading :
> FreeBSD bugs (ddurieux) :
>
>    - init files not copied in rc.d folder
>    - .shinken.ini seems incorrect Centos 7:
>    - Init scripts files seems incorrect (bad VAR and BIN vars)
>
> I will (wednesday) try to fix all of this, but if is too long, maybe the
> best option is to revert all of this ... :(
>
It was what I was to propose you. It's safer and so we will have plenty of
time to manage all the case :)


> But, I will continue with the idea that we should review (probably after
> the 2.4 release) what we should do/not do with the setup.py ...
>
> Please take a look on salt/ansible and other enterprise grade python
> softwares ...
> PLEASE ... ( sudo pip install salt ) ... PLEASE
>
I think we should not look at python projects (only). i don't really care
that's it's python (ven if it's my favorite language). We are building a
tool. The idea is what is the best place to install and what is the easier
way to install it. That's all, no matter it's written in GO or scala or
whatever :)

Of course python is technically impose us limitation (PYTHONPATH and such
things), but aside the python lib, we should behave as a classic tool, not
as a python tool only ^^

I'll get back the old setup.py and test in debian+centos if I don't miss a
part. Then it will be time for RC2 :p

**Comment by titilambert** [comment]
Well all is fixed for freeBSD
Now debian problem : could you answer me: you don't want to use the option:
```--install-option="--install-layout=deb"```
To install on debian/ubuntu ?

I'm working now on CentOS....

**Comment by titilambert** [comment]
@naparuba could you confirm you have/have not probrems with init script with centos 7 ?
Thanks !

**Comment by naparuba** [comment]
On Wed, Apr 8, 2015 at 7:57 PM, Thibault Cohen <notifications@github.com>
wrote:

> Well all is fixed for freeBSD
> Now debian problem : could you answer me: you don't want to use the option:
>
> To install on debian/ubuntu ?
>
> I'm working now on CentOS....
>
> You means the pip way with installlayout? Yes, it's not ok for
compatibilty. Users expect installation to not change at each release, as
they already script installation process and things like this.

So if the new way do not impact user and enhance dev why not, but here it
impacts users just for dev enhancement, it's not ok and you know it :)

So I'm putting the old setup.py so we can release a new RC, and we can take
more time to fix it for 2.6 :)

**Comment by titilambert** [comment]
Ok, revert it, I understand.
But I don't understand why you don't answer ....
@naparuba but please could you tell me what I have to do to have answers ??!!!!

**Comment by naparuba** [comment]
To which question? I did understand to all I saw unless I miss one.

**Comment by titilambert** [comment]
- @naparuba did you use : 
pip install https://github.com/titilambert/shinken/archive/sudo_setup_py.zip --install-option="--install-layout=deb" ?
- Could you answer me: you don't want to use the option:
--install-option="--install-layout=deb"
to install on debian/ubuntu ? @naparuba
- @naparuba could you confirm you have/have not probrems with init script with centos 7 ?

I don't see any answer ...

**Comment by gst** [comment]
> --install-option="--install-layout=deb"

at setup.py level - when/if it detects it's executed on a debian based distribution - if this option would be made a default (so to not have to give it manually), would it be more acceptable ?

**Comment by naparuba** [comment]
1&2: already answer when I said that install command should not change
between versions.

3: I already said that I won't test centos until debian is fixed.

**Comment by naparuba** [comment]
yes, if the command "python setup.py install" is still working will be ok
^^ No matter how the dev is doing (if at least maintenance is OK) but
should not change user "interface" and here people did create saltstack and
such things with "setup.py install" (and I don't even talk about the
several tutorials  with this command), so we should keep it as the top
level "view" for the user

Then what we are putting "inside" setup.py is our business ^^

**Pull request closed without merging**
