### PR TITLE
HTML mail notifications fix and improvements

### LINKED ISSUE #1745: Mail notification - encoding exception not catched
When message content is UTF-8 encoded an uncatched exception is raised and the mail notification is not sent. As an example: 
```
./notify_by_email.py -n service -S localhost -r test@localhost -f html -c "PROBLEM,,localhost,,127.0.0.1,,Mon 02 Nov 11:20:09 UTC 2015" -o "Services,,CRITICAL,,CRITICAL - 'Frédéric',,48h 05m 58s"

Traceback (most recent call last):
  File "/var/lib/shinken/libexec/notify_by_email.py", line 370, in <module>
    mail = create_html_message(mail)
  File "/var/lib/shinken/libexec/notify_by_email.py", line 228, in create_html_message
    html_msg = html_content.encode(sys.stdout.encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1783: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by mohierf**
- fix #1745 exception
- add an option to specify the mail sender (-s me@myserver.com) instead of default one
- use WebUI2 company logo if defined, or default logo if not
- use WebUI2 port for webui url
- add an option to specify the WebUI root part of URL
- updated doc

### CODE REVIEW

**Comment by olivierHa** [comment]
I've merged another PR with the sender option. I will merge this PR soon, after new travis tests

**Comment by mohierf** [comment]
I am quite disappointed with your merge strategy ... amongst the 3 PR dealing with a sender option, you choose not to merge this one which also included some fixes, a better integration with Web UI and some doc ! What a strange choice ...

**Comment by olivierHa** [comment]
Yes i am sorry about this one. My strategy was simple : start with the
small PR. I haven't expected to see 4 PR dealing with the sender
parameters.
Le 11 déc. 2015 5:20 AM, "Frédéric MOHIER" <notifications@github.com> a
écrit :

**Comment by hvad** [comment]
Why include that on shinken core ? I think you must use mod -> https://shinken.readthedocs.org/en/latest/14_contributing/modules.html.

**Comment by olivierHa** [comment]
@mohierf , could you manage the conflicts (again sorry about that :( ).
so i can merge this PR :)

**Comment by mohierf** [comment]
@olivierHa : I do not see any conflicts anymore now ...

**Comment by mohierf** [comment]
@olivierHa : I modified the PR and I see that there are still conflicts ... but I do not find them !

**Comment by mohierf** [comment]
I included #1749 modifications in the last commit of this PR.

**Comment by olivierHa** [comment]
Thanks a lot !

**Pull request merged**
