### PR TITLE
Fixes in dispatching the conf and external command in receiver.

### PR DESCRIPTION
**Pull request by andyxning**
I have made some fix commit about dispatching the conf and external command in receiver. Some of the commits are corresponding to the issues i issued before. some of them are:  #1493, #1491, #1490, #1489, #1483, #1431, #1430.

### CODE REVIEW

**Comment by titilambert** [comment]
Hello and Thanks !
Could you rebase you PR ?
Could you explain why you delete this line:
```
rec.put_conf(rec.cfg)
```

**Comment by andyxning** [comment]
@titilambert, i remove it because i think we have handled the receiver configurations and i think i has no reasonable to still send a configuration to receiver again. you can have [this](https://github.com/naparuba/shinken/pull/1503#commitcomment-9652339)

**Comment by Seb-Solon** [comment]
Hi

IMO this pull request is not acceptable like this. Did you have a look at this : https://shinken.readthedocs.org/en/latest/15_development/hackingcode.html#development-rules

We need tests case for such fixes, and clear cases. Fixing a bunch a bug in a single one commit is dangerous for regression. This is a pain understand and to debbug if necessary. 

Thanks for helping us :)

**Comment by andyxning** [comment]
@Seb-Solon , so if i split the commits in to PR, can you accept the PR?. The fact is something is not working correctly, so we should change this.

**Comment by Seb-Solon** [comment]
That's the first step yes. The other one is to provide tests for every fix you are doing. Because here test are all fine but bugs are in the code. If you can create a test that ensure the fix is done then we will be able to not undo your fix later :) Otherwise this fix may be broken by mistake one day.

Thanks

**Comment by Seb-Solon** [comment]
I merged some piece of this diff manually. Closing

**Comment by andyxning** [comment]
so, can you tell me about what piece did you have manually merged. i want
to know about it and find out what is left un-merged. Thanks.



++++++
Ning Xie


2015-04-02 4:35 GMT+08:00 Sébastien Coavoux <notifications@github.com>:

**Comment by Seb-Solon** [comment]
OK here are the detail of why I've closed that : 

Human timestamp => Nope as said before
Optimisation of sorting sattelite => #1493 On the 2.6 Roadmap as we were in freeze. The rework is already mentioned in the ticket
Dead code part => #1483 #1430 ON the 2.6 Roadmap. Not a fix so we postponed it
Arbiterlink => #1490 I'm not sure this one is legit still move to 2.6 Roadmap
External Command => #1489 Included see 918430c18c79e2137f6da846857cde0ce0f2adfa
Redis => Nope as I mentioned before

I think I forgot nothing regarding the PR content.

Now the PR itself : 
No tests => Nope, software development law
Can't automatically merge => Nope, spending time on merging conflict is always bad.
Multi fix PR=> Nope, for readibility 

So yeah I've actually not merged a lot but I've still dealt with all the issue (Yes/No/Postponed). I guess you have seen that in you notifications ;)

**Comment by andyxning** [comment]
ok, i got it. i think i can check out the new version about Shinken and
still working on unsolved problems.



++++++
Ning Xie


2015-04-02 10:27 GMT+08:00 Sébastien Coavoux <notifications@github.com>:

**Comment by naparuba** [comment]
Thanks :)

**Pull request closed without merging**
