### PR TITLE
Enh: scheduler: don't create unnecessarily (many) copies of services and...

### PR DESCRIPTION
**Pull request by gst**
... hosts when you want to iter over them

particularly this one:

for elt in [y for y in [x for x in self.hosts] + [x for x in self.services]]:

which create a first list copy of hosts,
also another list copy of services,
then create a third one being the sum of the 2 previous ( [..] + [..] )
then create a fourth one [y for y in [..]+[..] ]
then iterate over the last one.

On big configs (more than thousands of services or hosts) this could actually quite help.

### CODE REVIEW

**Comment by gst** [comment]
wait I've catched others places where the iter_hosts_and_services() can be also used..

**Comment by gst** [comment]
done.

**Comment by Seb-Solon** [comment]
It's ok for me !

**Comment by naparuba** [comment]
Valid, thanks :)

**Pull request merged**
