### PR TITLE
Test for 1576

### PR DESCRIPTION
**Pull request by k0ste**
https://github.com/naparuba/shinken/issues/1576

### CODE REVIEW

**Comment by naparuba** [comment]
Thanks, I'm giving a try :)

**Comment by naparuba** [comment]
Sorry but it's ok in my 2.4rc2:


root@shinken:~/shinken/test# python test_1576.py

################################################################################
#                                                                              #
#                        __main__.TestConfig.test_dummy                        #
#                                                                              #
################################################################################

[1429626835] ERROR: [Shinken] [items] Service INTERFACE-$KEY$-STATE not found for host test_host_0
[1429626835] ERROR: [Shinken]   servicedependencies conf incorrect!!
The conf is not correct, I stop here
Get the hosts and services
E
======================================================================
ERROR: test_dummy (__main__.TestConfig)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_1576.py", line 40, in test_dummy
    host = self.sched.hosts.find_by_name("test_host_0")
AttributeError: 'TestConfig' object has no attribute 'sched'

----------------------------------------------------------------------
Ran 1 test in 0.241s

FAILED (errors=1)

Can you be sure it fail with a 2.4rc2 version (be sure to setup.py install it).

I postpone this to 2.6 until we can reproduce it :)

**Comment by gst** [comment]
ho well.. I tried this new test on the commit 1c8e11a and then on the next one (7c32e8e871) and on the first one I already got an error : 
```
gstarck@taf 10:53 $ git st && nosetests test_1576.py
HEAD détachée sur 1c8e11a
rien à valider, la copie de travail est propre
E
======================================================================
ERROR: test_dummy (test_1576.TestConfig)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gstarck/work/work/SFL/Supervision/shinken/test/test_1576.py", line 40, in test_dummy
    host = self.sched.hosts.find_by_name("test_host_0")
AttributeError: 'TestConfig' object has no attribute 'sched'
-------------------- >> begin captured stdout << ---------------------

################################################################################
#                                                                              #
#                       test_1576.TestConfig.test_dummy                        #
#                                                                              #
################################################################################

[1429628032] ERROR: [Shinken] [itemgroup::servicegroup-dns] as servicegroup, got unknown member test_host_0,DNS-RESOLVER
[1429628032] ERROR: [Shinken] [items] In servicegroup-dns is incorrect ; from unknown
[1429628032] ERROR: [Shinken] 	servicegroups conf incorrect!!
[1429628032] ERROR: [Shinken] [items] Service DNS-RESOLVER not found for host test_host_0
[1429628032] ERROR: [Shinken] 	servicedependencies conf incorrect!!
The conf is not correct, I stop here
```

and the next one, it just fail the same way.. but travis has not failed on its side (I've just relaunched it) :s  .. to be investigated..

**Comment by k0ste** [comment]
```
Can you be sure it fail with a 2.4rc2 version (be sure to setup.py install it).
```
Tested on 2.4rc2. All ok :)

```
[1429675025] ERROR: [Shinken] [items] Service INTERFACE-$KEY$-STATE not found for host test_host_0
[1429675025] ERROR: [Shinken] 	servicedependencies conf incorrect!!
The conf is not correct, I stop here
```

**Pull request closed without merging**
