### PR TITLE
Tests simplify livestatus - in branch1.4

### PR DESCRIPTION
**Pull request by gst**
This bring 2 main things  : 

1) livestatus tests: factorized quite a lot + simplified (as possible) + cleaned (a bit with the factorization).

2) jenkins new_runtest.sh (backported from https://github.com/gst/shinken/tree/jenkins_and_python26 ) :
 + with 2 new main features : 
      a) possibility to test with a different python version than the system one (define JENKINS_PYTHON env var).
      b) possibility to fail fast (define FAILFAST=1 env var).

With this every test configuration is ok : 
Travis + Jenkins (short & long) , on python2.6 as well as on 2.7

### CODE REVIEW

**Comment by gst** [comment]
@naparuba  ?  :p 

if you would like I can take care of this branch-1.4  : maintenance, review PRs (well, there are only from me actually), etc..

**Comment by Seb-Solon** [comment]
can't merge :/

**Comment by gst** [comment]
huh... give me a free moment and I'll recheck..

**Comment by gst** [comment]
was 2 "bits". rebased that. 

should merge now.

**Pull request merged**
