### PR TITLE
Fix setup.py to handle sudo python setup.py install #1555

### PR DESCRIPTION
**Pull request by titilambert**
Hello !

This fix the bug #1555

Could you confirm it ?

### CODE REVIEW

**Comment by naparuba** [comment]
Nearly, just an issue on the scripts directory:


root@ns331928:~/shinken# python setup.py install

Installing shinken-receiver script to /usr/local/bin
Installing shinken script to /usr/local/bin
Installing shinken-reactionner script to /usr/local/bin
Installing shinken-poller script to /usr/local/bin
Installing shinken-arbiter script to /usr/local/bin
Installing shinken-scheduler script to /usr/local/bin
Installing shinken-broker script to /usr/local/bin
[...]

root@ns331928:~/shinken# /etc/init.d/shinken start
Starting scheduler:
FAILED: did not find scheduler file (/usr/bin/shinken-scheduler) ; are you sure shinken-scheduler is installed? ... failed!
 failed!
Starting poller:
FAILED: did not find poller file (/usr/bin/shinken-poller) ; are you sure shinken-poller is installed? ... failed!
 failed!
Starting reactionner:
FAILED: did not find reactionner file (/usr/bin/shinken-reactionner) ; are you sure shinken-reactionner is installed? ... failed!
 failed!
Starting broker:
FAILED: did not find broker file (/usr/bin/shinken-broker) ; are you sure shinken-broker is installed? ... failed!
 failed!
Starting receiver:
FAILED: did not find receiver file (/usr/bin/shinken-receiver) ; are you sure shinken-receiver is installed? ... failed!
 failed!
Starting arbiter:
FAILED: did not find arbiter file (/usr/bin/shinken-arbiter) ; are you sure shinken-arbiter is installed? ... failed!
 failed!

**Comment by naparuba** [comment]
ps: seems that travis is not happy (setup need the shinken user).

I did add TRAVIS=1 variable on the travis configuration, so we can hok this env variable to skip shinken user raise on the setup.py :)

**Comment by titilambert** [comment]
Could tell me which distro you use ?

**Comment by titilambert** [comment]
I closed this PR and opened this one #1561

**Pull request closed without merging**
