### PR TITLE
Shinken default notification plugin

### PR DESCRIPTION
**Pull request by claneys**
Shinken email notification plugin.

It send notification in a txt or html format, including url to webui if wanted and add a logo at the top to include by example customer company logo.

### CODE REVIEW

**Comment by mohierf** [comment]
+1 for this feature

**Comment by olivierHa** [comment]
Seems great ! +1 too

**Comment by claneys** [comment]
A bit late but it's merged. Hope that you enjoy it :)

**Comment by olivierHa** [comment]
Hum, ok to change the "detailled email" command, but changing the default notification could raise issues with python dependencies, don't you think ?

**Comment by claneys** [comment]
It seems not, because it uses only generic modules or already installed shinken dependencies. Do you see something weird ?

**Comment by hvad** [comment]
Hi,

Why not write a special module for notification ?

Best regard

2015-07-16 13:46 GMT+02:00 Forlot Romain <notifications@github.com>:

> It seems not, because it uses only generic modules or already installed
> shinken dependencies. Do you see something weird ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/naparuba/shinken/pull/1653#issuecomment-121933800>.
>



-- 
David Hannequin

**Pull request merged**
