### PR TITLE
Clean facto get initial status brok

### PR DESCRIPTION
**Pull request by gst**
A small but good DRY pass.

### CODE REVIEW

**Comment by gst** [comment]
By the way : 

I'm asking myself why some classes aren't also part of shinken.objects (i.e : subclass Item) , like  :

+ Action (action.py)
+ Acknowledge (acknowledge.py)
+ Check (check.py ; subclass Action so if Action is done this one also)
+ Comment
+ ContactDowntime
+ Downtime
+ Notification (same than Check)

and that's all I think..

**Comment by gst** [comment]
@naparuba ?

**Comment by gst** [comment]
rebased on master because of merge conflict with last PEP8 work.

**Comment by gst** [comment]
pep8 fixed.

**Comment by naparuba** [comment]
travis in progress. Merge after done :)

**Comment by titilambert** [comment]
@gst nice ! maybe, later, one day, shinken wil be a one liner ??? :D

**Comment by naparuba** [comment]
done :)

**Comment by gst** [comment]
> one day, shinken wil be a one liner ??? :D

hmm.. I doubt, just slightly.. ;)

**Pull request merged**
