### PR TITLE
Shinken 2.4.1 html dependency

### PR DESCRIPTION
**Pull request by k0ste**
New html notifications required [this](https://pypi.python.org/pypi/html).

### CODE REVIEW

**Comment by hvad** [comment]
Hi,

I don't think HTML Notification is necessary for monitoring tool. 

Best regard

**Comment by k0ste** [comment]
It's already required by #1653 because is default for Shinken 2.4.1

**Comment by claneys** [comment]
My bad, forgot that requirement. Thanks you !

**Comment by hvad** [comment]
Hi don"t agree with this commit because HTML notification is not good idea and non sense with webui2.

**Comment by k0ste** [comment]
@hvad, for this time Shinken user can't make choice, html or not #1653.

**Pull request merged**
