### PR TITLE
Adding notifications on Slack

### PR DESCRIPTION
**Pull request by fakhruddinhamid**
This plugin will help to deliver the notification for hosts / services on slack channel.
Define a contact which will use slack notifications way and channel name could be defined in the commands/*

Hope this will help some one who is looking to send alerts to Slack.

### CODE REVIEW

**Comment by fakhruddinhamid** [comment]
I re-submitted the merge after first one failed as I had put in hard code dependency on python 2.7
I hope you can re-run the scrutinizer to resolve this.

Let me know if i can do some thing to resolve.

**Comment by hvad** [comment]
Please create mod.

**Comment by fakhruddinhamid** [comment]
Hi Hvad,
Sorry but I didn't get as what you meant by create mod.
It would be great if you could elaborate more on as how could I resolve this.

I realise the mistake I did was closed the orginal merge and recreated one more with just a small change and this resulted in duplicate error in Scrutinizer.

-Fakhruddin Hamid

**Comment by hvad** [comment]
Hi,

You can see on http://shinken.io/ mod for shinken core. You can't include feature like that on core shinken. 

Documentation to make mod -> https://shinken.readthedocs.org/en/latest/14_contributing/modules.html

**Comment by fakhruddinhamid** [comment]
Hi,
Thanks for guiding, I will publish a mod.

**Pull request closed without merging**
