### PR TITLE
notify_by_email improvements

### PR DESCRIPTION
**Pull request by saez0pub**
Hello,

I'm using a smtps server with login auth, so notify_by_email does,'t work.
I alreday have ssmtp which forwards the system mails. It provides a sendmail command line compatible whith the real sendmail.
Updating the mail script was necessary.
More, the sender wan be configurable.

Jean Prat.

### CODE REVIEW

**Comment by olivierHa** [comment]
I've merged another PR with a sender option. Could you update this PR according to new master upstream ?

**Comment by hvad** [comment]
Why include that on shinken core ? I think you must use mod -> https://shinken.readthedocs.org/en/latest/14_contributing/modules.html.

**Comment by olivierHa** [comment]
hvad, I think this is the right "space"
I think we should provide at least a "decent" mail sender in shinken core. 
I agree that we can't support every "alternative" (irc,jabber ....) notification system, but email notification should be included and supported in shinken "core".

**Comment by mohierf** [comment]
@saez0pub : I included your sendmail modifications in the #1746

**Comment by olivierHa** [comment]
This has been merged within another PR. Thanks !

**Pull request closed without merging**
