### PR TITLE
Backport mod-livestatus to branch 1.4

### PR DESCRIPTION
**Pull request by gst**
Done in 4 steps for 4 main changes (and for easier debug/understanding).

Travis already OK with this.
Think it may be good for a manual test now, with Thruk and CheckMk (what else ?).

Have another branch where I'm trying to get jenkins (long) tests also ok.. (WIP).

### CODE REVIEW

**Comment by gst** [comment]
All 3 first commits have been tested ok under travis:

part 1 : https://travis-ci.org/gst/shinken/builds/46210873
part 2 : https://travis-ci.org/gst/shinken/builds/46213107
part 3 : https://travis-ci.org/gst/shinken/builds/46213462

**Comment by gst** [comment]
I will add/backport the last commit from https://github.com/shinken-monitoring/mod-livestatus/commit/3c0dbdb5e20483f698d421f66f28cea01f4db89a

and then after there will only be left the adaptations needed for jenkins tests.. which also requires some changes/backport from shinken master or so.. (you don't get an omelette without "breaking eggs").

**Comment by naparuba** [comment]
let me know when it's ok and we will merge so :)

**Comment by gst** [comment]
youhhhouuuu, this is going better and better : 

https://test.savoirfairelinux.com/view/Shinken/job/Shinken-with-jenkins/196/testReport/
(think these tests were already bad previously)

..approaching victory so :p
(on a temp branch for now: https://github.com/gst/shinken/commit/a287a12180163e60baedc3d93e3fbd74b5fc81ee )

**Comment by gst** [comment]
python2.6 tests reactived on branch1.4 : 

https://travis-ci.org/gst/shinken/builds/46495140

and they pass Travis !

**Comment by gst** [comment]
Here it is.

+ Travis with python2.6 and python2.7 OK !
+ Jenkins (with python2.7) also OK !

Hourah ! 

Even if it's really temporary: branch 1.4 tests are now back to a clear better state ;)

**Comment by gst** [comment]
laddies and gentleman, 

who wants to merge ? :D 

come on, the tests pass on travis+jenkins ;)

**Pull request merged**
